# Generated by Django 5.1 on 2024-09-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('which_class', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
